# 타로 카드 데이터

tarot_cards = [
    {
        "name": "0. 바보",
        "meaning": "새로운 시작, 모험, 순수함",
        "description": "새로운 여정의 시작을 의미합니다. 두려움 없이 앞으로 나아가세요. 때로는 경험 없이 시작하는 것이 더 큰 가능성을 열어줍니다.",
        "image_file": "00_fool.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/04/05/22/42/the-fool-6154764_1280.jpg",
    },
    {
        "name": "I. 마법사",
        "meaning": "창의성, 기술, 의지력",
        "description": "당신의 재능과 능력을 활용할 때입니다. 자신감을 가지고 자신의 기술을 발휘하세요. 모든 요소가 당신의 손 안에 있습니다.",
        "image_file": "01_magician.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/04/05/22/42/the-magician-6154763_1280.jpg",
    },
    {
        "name": "II. 여사제",
        "meaning": "직관, 지혜, 비밀",
        "description": "내면의 목소리에 귀를 기울이세요. 직관이 당신을 인도합니다. 표면 아래의 지혜를 찾고 내면의 지식을 신뢰하세요.",
        "image_file": "02_high_priestess.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/04/05/22/42/the-high-priestess-6154767_1280.jpg",
    },
    {
        "name": "III. 여황제",
        "meaning": "풍요, 안정, 모성",
        "description": "풍요와 성장의 시기입니다. 자신과 주변을 돌보세요. 안정과 번영이 당신을 기다리고 있습니다. 자연과의 조화를 찾으세요.",
        "image_file": "03_empress.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/04/05/22/42/the-empress-6154768_1280.jpg",
    },
    {
        "name": "IV. 황제",
        "meaning": "권위, 구조, 통제",
        "description": "안정과 질서를 확립할 때입니다. 리더십을 발휘하고 상황을 통제하세요. 규칙과 구조가 당신의 성공을 도울 것입니다.",
        "image_file": "04_emperor.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/04/05/22/42/the-emperor-6154771_1280.jpg",
    },
    {
        "name": "V. 교황",
        "meaning": "전통, 신념, 도덕성",
        "description": "정신적 가르침과 지혜를 구하세요. 전통적 가치를 존중하고 도덕적 지침을 따르세요. 멘토나 스승의 조언이 도움이 될 것입니다.",
        "image_file": "05_hierophant.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/04/05/22/42/the-hierophant-6154772_1280.jpg",
    },
    {
        "name": "VI. 연인들",
        "meaning": "사랑, 조화, 선택",
        "description": "중요한 선택의 시기입니다. 마음을 따르되 신중하게 결정하세요. 사랑과 관계에서 조화를 찾고 진정한 가치를 추구하세요.",
        "image_file": "06_lovers.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/04/05/22/43/the-lovers-6154774_1280.jpg",
    },
    {
        "name": "VII. 전차",
        "meaning": "의지력, 성공, 결단력",
        "description": "목표를 향해 전진하세요. 승리가 당신을 기다립니다. 의지력과 결단력으로 장애물을 극복하고 성공을 향해 나아가세요.",
        "image_file": "07_chariot.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/04/05/22/43/the-chariot-6154775_1280.jpg",
    },
    {
        "name": "VIII. 힘",
        "meaning": "용기, 인내, 영향력",
        "description": "내면의 힘을 발견하세요. 인내와 용기로 어려움을 극복할 수 있습니다. 강인함과 부드러움의 균형을 찾으세요.",
        "image_file": "08_strength.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/04/05/22/43/strength-6154776_1280.jpg",
    },
    {
        "name": "IX. 은둔자",
        "meaning": "성찰, 내면의 탐색, 고독",
        "description": "자신을 돌아보고 내면의 지혜를 찾으세요. 고독은 때로 필요합니다. 조용한 시간을 통해 깊은 통찰을 얻을 수 있습니다.",
        "image_file": "09_hermit.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/04/05/22/43/the-hermit-6154777_1280.jpg",
    },
    {
        "name": "X. 운명의 수레바퀴",
        "meaning": "운명, 순환, 전환점",
        "description": "변화가 다가오고 있습니다. 운명의 흐름을 받아들이세요. 인생의 순환을 이해하고 새로운 기회를 포착하세요.",
        "image_file": "10_wheel_of_fortune.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/05/13/06/38/tarot-6249967_1280.jpg",
    },
    {
        "name": "XI. 정의",
        "meaning": "균형, 진실, 공정함",
        "description": "공정함과 균형을 추구하세요. 진실은 항상 드러납니다. 자신의 행동에 책임을 지고 정의로운 결정을 내리세요.",
        "image_file": "11_justice.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/05/13/06/38/tarot-6249968_1280.jpg",
    },
    {
        "name": "XII. 매달린 사람",
        "meaning": "희생, 새로운 관점, 기다림",
        "description": "다른 관점에서 상황을 바라보세요. 때로는 기다림이 필요합니다. 자발적인 희생을 통해 더 큰 지혜를 얻을 수 있습니다.",
        "image_file": "12_hanged_man.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/05/13/06/38/tarot-6249969_1280.jpg",
    },
    {
        "name": "XIII. 죽음",
        "meaning": "변화, 종결, 변형",
        "description": "끝은 새로운 시작을 의미합니다. 변화를 두려워하지 마세요. 오래된 것을 놓아주고 새로운 가능성을 받아들이세요.",
        "image_file": "13_death.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/05/13/06/38/tarot-6249972_1280.jpg",
    },
    {
        "name": "XIV. 절제",
        "meaning": "균형, 조화, 중용",
        "description": "균형과 조화를 찾으세요. 극단을 피하고 중용을 지키세요. 인내와 절제를 통해 장기적인 성공을 이룰 수 있습니다.",
        "image_file": "14_temperance.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/05/13/06/39/tarot-6249973_1280.jpg",
    },
    {
        "name": "XV. 악마",
        "meaning": "속박, 유혹, 그림자 자아",
        "description": "자신을 속박하는 것이 무엇인지 인식하세요. 유혹에 주의하고 자신의 그림자 측면을 이해하세요. 진정한 자유를 찾으세요.",
        "image_file": "15_devil.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/05/13/06/39/tarot-6249974_1280.jpg",
    },
    {
        "name": "XVI. 탑",
        "meaning": "갑작스러운 변화, 혼란, 계시",
        "description": "예상치 못한 변화가 올 수 있습니다. 이를 통해 성장할 수 있습니다. 오래된 구조가 무너져도 새로운 기회가 열립니다.",
        "image_file": "16_tower.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/05/13/06/39/tarot-6249975_1280.jpg",
    },
    {
        "name": "XVII. 별",
        "meaning": "희망, 영감, 평온",
        "description": "희망과 영감의 시간입니다. 미래는 밝습니다. 자신의 꿈을 믿고 영적인 안내를 받아들이세요.",
        "image_file": "17_star.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/05/13/06/39/tarot-6249976_1280.jpg",
    },
    {
        "name": "XVIII. 달",
        "meaning": "환상, 불확실성, 직관",
        "description": "표면 아래의 진실을 찾으세요. 직관을 믿되 환상에 속지 마세요. 무의식의 메시지에 귀를 기울이세요.",
        "image_file": "18_moon.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/05/13/06/39/tarot-6249977_1280.jpg",
    },
    {
        "name": "XIX. 태양",
        "meaning": "성공, 기쁨, 활력",
        "description": "성공과 행복의 시기입니다. 자신의 빛을 발하세요. 긍정적인 에너지가 당신을 둘러싸고 있습니다.",
        "image_file": "19_sun.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/05/13/06/39/tarot-6249979_1280.jpg",
    },
    {
        "name": "XX. 심판",
        "meaning": "재생, 각성, 용서",
        "description": "과거를 용서하고 새로운 시작을 준비하세요. 자신을 재발견할 때입니다. 진정한 소명을 찾고 새로운 단계로 나아가세요.",
        "image_file": "20_judgement.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/10/06/23/00/judgement-6686819_1280.jpg",
    },
    {
        "name": "XXI. 세계",
        "meaning": "완성, 성취, 통합",
        "description": "목표 달성과 완성의 시기입니다. 당신의 여정이 결실을 맺습니다. 모든 요소가 조화롭게 통합되어 성취감을 느낄 것입니다.",
        "image_file": "21_world.jpg",
        "image_url": "https://cdn.pixabay.com/photo/2021/10/06/23/00/the-world-6686820_1280.jpg",
    },
]
